remote_theme: tedivm/jekyll-theme-portfolio


title: Connor Pennington
author: Connor Pennington
email: cjpenni@clemson.edu
description: >
  Connor Pennington Project Portfolio Website


homepage: https://cjpenni.github.io
github_username: cjpenni
linkedin_username: connor-j-pennington


plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme
