remote_theme: tedivm/jekyll-theme-portfolio


title: Your awesome title
author: Your Name
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.


homepage: https://your.homepage.com
github_username: cjpenni
linkedin_username: Connor Pennington


plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme
