# Basic Jekyll configuration without remote theme
title: Connor Pennington
author: Connor Pennington
email: cjpenni@clemson.edu
description: >
  Connor Pennington - Computer Science Student & AI Enthusiast

url: "https://connorpennington.dev"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files
exclude:
  - README.md
  - .gitignore